DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "https://hawaiihow.com"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
theme = "ananke"
title = "Hawaii How"
[params]
background_color_class = "bg-black"
description = "A great guide to Hawaii"
facebook = ""
favicon = ""
featured_image = "/uploads/2018/01/16/gohugo-default-sample-hero-image.jpg"
github = ""
instagram = ""
linkedin = ""
recent_posts_number = 2
twitter = "https://twitter.com/hawaiihow"
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
